name: CI - PGATS-02-API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install
      - name: Instalar mochawesome
        run: npm install mochawesome --save-dev
      - name: Rodar testes e gerar relatório HTML
        run: npx mocha "test/**/*.js" --reporter mochawesome
      - name: Salvar relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report
