name: CI - PGATS-02-API
permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      # Testes de Controller
      - name: Rodar testes do Controller
        run: npm run test-controller -- --reporter mocha-junit-reporter --reporter-options mochaFile=results-controller.xml

      - name: Publicar relatório Controller
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Controller Tests
          path: results-controller.xml
          reporter: java-junit

      # Subir a API para os testes de integração
      - name: Subir API
        run: npm start &

      - name: Esperar API estar funcionando
        run: sleep 5

      # Testes de Integração
      - name: Rodar testes de Integração
        run: npm run test-integration -- --reporter mocha-junit-reporter --reporter-options mochaFile=results-integration.xml

      - name: Publicar relatório Integração
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: results-integration.xml
          reporter: java-junit
