name: CI - PGATS-02-API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install
      - name: Instalar mocha-junit-reporter
        run: npm install mocha-junit-reporter --save-dev
      - name: Rodar testes e gerar relatório JUnit
        run: npx mocha "test/**/*.js" --reporter mocha-junit-reporter --reporter-options mochaFile=results.xml
      - name: Publicar relatório visual no summary
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Mocha Tests
          path: results.xml
          reporter: java-junit
